"""Synthetic fixture determinism, realistic structure, and planted canaries."""

import json

from tests.fixtures import NEW_CANARY_CLASSES, generate_fixtures


def tree_bytes(root):
    return {
        str(p.relative_to(root)): p.read_bytes() for p in sorted(root.rglob("*")) if p.is_file()
    }


def test_generator_is_deterministic(tmp_path):
    a = generate_fixtures(tmp_path / "a", seed=1)
    b = generate_fixtures(tmp_path / "b", seed=1)
    assert tree_bytes(a.root) == tree_bytes(b.root)
    assert a.content_canaries == b.content_canaries
    assert a.nonce_canaries == b.nonce_canaries
    assert a.new_canaries == b.new_canaries
    assert [p.relative_to(a.root) for p in a.lifecycle_event_streams] == [
        p.relative_to(b.root) for p in b.lifecycle_event_streams
    ]
    assert [p.relative_to(a.root) for p in a.git_evidence_files] == [
        p.relative_to(b.root) for p in b.git_evidence_files
    ]
    assert [p.relative_to(a.root) for p in a.plan_orchestration_files] == [
        p.relative_to(b.root) for p in b.plan_orchestration_files
    ]


def test_different_seeds_differ(tmp_path):
    a = generate_fixtures(tmp_path / "a", seed=1)
    b = generate_fixtures(tmp_path / "b", seed=2)
    assert a.content_canaries != b.content_canaries
    assert a.new_canaries != b.new_canaries


def test_generation_is_independent_of_destination_repo_and_filename(tmp_path):
    # Different destination strings stand in for arbitrary local repo/file
    # names. Equal relative trees prove no ambient path or source file enters
    # the generated bytes or names; only the explicit seed does.
    first = generate_fixtures(tmp_path / "unrelated-local-repo-a", seed=7)
    second = generate_fixtures(tmp_path / "different-worktree-b", seed=7)
    assert tree_bytes(first.root) == tree_bytes(second.root)
    corpus = b"".join(tree_bytes(first.root).values())
    assert b"unrelated-local-repo-a" not in corpus
    assert b"different-worktree-b" not in corpus


def test_claude_sessions_shaped_like_jsonl_transcripts(tmp_path):
    fx = generate_fixtures(tmp_path)
    claude = [s for s in fx.sessions if "claude" in s.parts]
    assert claude
    for session in claude:
        lines = [json.loads(ln) for ln in session.read_text().splitlines()]
        assert lines
        for line in lines:
            assert line["type"] in {"user", "assistant"}
            assert {"uuid", "timestamp", "sessionId", "message", "cwd"} <= line.keys()


def test_codex_sessions_shaped_like_jsonl_transcripts(tmp_path):
    fx = generate_fixtures(tmp_path)
    codex = [s for s in fx.sessions if "codex" in s.parts]
    assert codex
    for session in codex:
        lines = [json.loads(ln) for ln in session.read_text().splitlines()]
        assert lines
        for line in lines:
            assert {"timestamp", "type", "payload"} <= line.keys()
        assert [line["type"] for line in lines] == [
            "session_meta",
            "turn_context",
            "response_item",
            "response_item",
            "response_item",
            "response_item",
            "event_msg",
            "event_msg",
        ]
        assert lines[0]["payload"]["model_provider"] == "openai"
        assert lines[1]["payload"]["model"] == "gpt-5-codex"
        assert lines[2]["payload"]["role"] == "user"
        assert lines[3]["payload"]["role"] == "assistant"
        assert lines[4]["payload"]["type"] == "function_call"
        assert lines[5]["payload"]["type"] == "function_call_output"
        assert lines[6]["payload"]["type"] == "token_count"
        assert lines[7]["payload"]["type"] == "context_compacted"


def test_lifecycle_streams_have_claude_hook_and_codex_rollout_shapes(tmp_path):
    fixtures = generate_fixtures(tmp_path)
    assert len(fixtures.lifecycle_event_streams) == 2
    claude = next(path for path in fixtures.lifecycle_event_streams if "claude" in path.name)
    codex = next(path for path in fixtures.lifecycle_event_streams if "codex" in path.name)
    claude_rows = [json.loads(line) for line in claude.read_text().splitlines()]
    codex_rows = [json.loads(line) for line in codex.read_text().splitlines()]
    assert [row["hook_event_name"] for row in claude_rows] == [
        "SessionStart",
        "PreCompact",
        "SessionEnd",
    ]
    assert all(
        {"session_id", "transcript_path", "cwd", "observed_at"} <= row.keys() for row in claude_rows
    )
    assert [row["type"] for row in codex_rows] == [
        "session_meta",
        "response_item",
        "response_item",
        "event_msg",
    ]
    assert codex_rows[-1]["payload"] == {"type": "task_complete"}


def test_git_evidence_tree_has_repo_worktree_and_branch_shapes(tmp_path):
    fixtures = generate_fixtures(tmp_path)
    assert len(fixtures.git_evidence_files) == 1
    evidence = json.loads(fixtures.git_evidence_files[0].read_text())
    assert evidence["synthetic"] is True
    assert evidence["repository"]["name"] == fixtures.canary("repo_name").decode()
    assert evidence["worktrees"][0]["name"] == fixtures.canary("worktree_name").decode()
    assert evidence["worktrees"][0]["branch"] == fixtures.canary("branch_name").decode()


def test_plan_instruction_and_orchestration_file_tree_is_complete(tmp_path):
    fixtures = generate_fixtures(tmp_path)
    assert len(fixtures.plan_orchestration_files) == 3
    relative = {str(path.relative_to(fixtures.root)) for path in fixtures.plan_orchestration_files}
    assert any("planning/plans/" in path for path in relative)
    assert any("planning/instructions/" in path for path in relative)
    assert any("planning/orchestration/" in path for path in relative)


def test_fixtures_embed_content_filename_and_low_entropy_canaries(tmp_path):
    fx = generate_fixtures(tmp_path)
    corpus = b"".join(s.read_bytes() for s in fx.sessions)
    assert any(c.encode() in corpus for c in fx.content_canaries)
    assert any(f.encode() in corpus for f in fx.filename_canaries)
    assert any(line.encode() in corpus for line in fx.low_entropy_lines)


def test_nonce_canaries_are_adr0002_shaped_and_not_in_transcripts(tmp_path):
    fx = generate_fixtures(tmp_path)
    corpus = b"".join(s.read_bytes() for s in fx.sessions)
    assert len(fx.nonce_canaries) >= 2
    for nonce in fx.nonce_canaries:
        assert len(nonce) == 32  # ADR-0002 §1
        # Nonces are pipeline inputs, not transcript content — they must not
        # start out inside the fixtures or every later scan would false-fire.
        assert nonce not in corpus and nonce.hex().encode() not in corpus


def test_all_canaries_covers_every_kind(tmp_path):
    fx = generate_fixtures(tmp_path)
    allc = fx.all_canaries()
    assert tuple(fx.new_canaries) == NEW_CANARY_CLASSES
    assert len(allc) == (
        len(fx.content_canaries)
        + len(fx.filename_canaries)
        + len(fx.nonce_canaries)
        + len(NEW_CANARY_CLASSES)
    )
    assert all(isinstance(c, bytes) for c in allc)


def test_every_new_canary_is_planted_in_fixture_bytes_or_path(tmp_path):
    fixtures = generate_fixtures(tmp_path)
    file_bytes = [path.read_bytes() for path in fixtures.root.rglob("*") if path.is_file()]
    file_paths = [
        str(path.relative_to(fixtures.root)).encode() for path in fixtures.root.rglob("*")
    ]
    corpus = b"\n".join((*file_bytes, *file_paths))
    assert all(fixtures.canary(class_name) in corpus for class_name in NEW_CANARY_CLASSES)
