"""Deterministic, content-opaque Claude, Codex, and Git normalization."""

from mybench.normalizer.claude import (
    CLAUDE_ADAPTER_VERSION,
    ContentResolution,
    ResolutionIntegrityError,
    ResolutionRecord,
    VerifiedRecord,
    VerifiedSession,
    normalize_claude,
    resolve_content_pointer,
    resolution_coverage,
)
from mybench.normalizer.contract import (
    AUTHORSHIP_POLICY_VERSION,
    EPISODE_STITCHER_VERSION,
    NORMALIZER_VERSION,
    TOKEN_ACCOUNTING_POLICY_VERSION,
    NoEvidence,
    NormalizationError,
    validate_corpus_artifact,
    token_accounting_includes,
)
from mybench.normalizer.codex import CODEX_ADAPTER_VERSION, normalize_codex
from mybench.normalizer.repo import (
    GIT_ADAPTER_VERSION,
    REPO_NORMALIZER_VERSION,
    CommitEvidence,
    RefEvidence,
    RepoTarget,
    VerifiedRepoSnapshot,
    WorktreeEvidence,
    normalize_repo_evidence,
    validate_repo_corpus_artifact,
)

__all__ = [
    "AUTHORSHIP_POLICY_VERSION",
    "CLAUDE_ADAPTER_VERSION",
    "CODEX_ADAPTER_VERSION",
    "CommitEvidence",
    "ContentResolution",
    "EPISODE_STITCHER_VERSION",
    "NORMALIZER_VERSION",
    "TOKEN_ACCOUNTING_POLICY_VERSION",
    "NoEvidence",
    "NormalizationError",
    "ResolutionIntegrityError",
    "ResolutionRecord",
    "GIT_ADAPTER_VERSION",
    "REPO_NORMALIZER_VERSION",
    "RefEvidence",
    "RepoTarget",
    "VerifiedRecord",
    "VerifiedRepoSnapshot",
    "VerifiedSession",
    "WorktreeEvidence",
    "normalize_claude",
    "normalize_codex",
    "normalize_repo_evidence",
    "resolve_content_pointer",
    "resolution_coverage",
    "token_accounting_includes",
    "validate_corpus_artifact",
    "validate_repo_corpus_artifact",
]
