"""Deterministic, content-opaque Claude, Codex, and Git normalization."""

from mybench.normalizer.claude import (
    CLAUDE_ADAPTER_VERSION,
    ContentResolution,
    GitBindingObservation,
    ResolutionIntegrityError,
    ResolutionRecord,
    VerifiedRecord,
    VerifiedSession,
    classify_forge_invocation,
    normalize_claude,
    resolve_content_pointer,
    resolution_coverage,
)
from mybench.normalizer.contract import (
    ARRIVAL_PATTERN_CLASSIFIER_VERSION,
    ARRIVAL_PATTERN_TAXONOMY_VERSION,
    AUTHORSHIP_POLICY_VERSION,
    EPISODE_STITCHER_VERSION,
    EPISODE_OPEN_MARKER_VERSION,
    EPISODE_OUTCOME_CLASSIFIER_VERSION,
    FORGE_ACTION_CLASSIFIER_VERSION,
    NORMALIZER_VERSION,
    TOKEN_ACCOUNTING_POLICY_VERSION,
    NoEvidence,
    NormalizationError,
    validate_corpus_artifact,
    token_accounting_includes,
)
from mybench.normalizer.codex import CODEX_ADAPTER_VERSION, normalize_codex
from mybench.normalizer.repo import (
    GIT_ADAPTER_VERSION,
    REPO_NORMALIZER_VERSION,
    CommitEvidence,
    RefEvidence,
    RepoTarget,
    VerifiedRepoSnapshot,
    WorktreeEvidence,
    normalize_repo_evidence,
    validate_repo_corpus_artifact,
)
from mybench.normalizer.reference_join import (
    REFERENCE_JOIN_NORMALIZER_VERSION,
    ReferenceTargetJoin,
    normalize_reference_target_joins,
    validate_reference_target_corpus_artifact,
)
from mybench.normalizer.session_timing import (
    SESSION_TIMING_NORMALIZER_VERSION,
    SessionTiming,
    normalize_session_timing_bytes,
    normalize_session_timings,
)
from mybench.normalizer.workflow_phase import (
    WORKFLOW_PHASE_CLASSIFIER_VERSION,
    WORKFLOW_PHASE_CONFIDENCE,
    WORKFLOW_PHASE_SCHEMA_VERSION,
    WORKFLOW_PHASES,
    WorkflowPhase,
    classify_workflow_phases,
    workflow_phase_artifact,
)

__all__ = [
    "ARRIVAL_PATTERN_CLASSIFIER_VERSION",
    "ARRIVAL_PATTERN_TAXONOMY_VERSION",
    "AUTHORSHIP_POLICY_VERSION",
    "CLAUDE_ADAPTER_VERSION",
    "CODEX_ADAPTER_VERSION",
    "CommitEvidence",
    "ContentResolution",
    "GitBindingObservation",
    "EPISODE_STITCHER_VERSION",
    "EPISODE_OPEN_MARKER_VERSION",
    "EPISODE_OUTCOME_CLASSIFIER_VERSION",
    "FORGE_ACTION_CLASSIFIER_VERSION",
    "NORMALIZER_VERSION",
    "TOKEN_ACCOUNTING_POLICY_VERSION",
    "WORKFLOW_PHASE_CLASSIFIER_VERSION",
    "WORKFLOW_PHASE_CONFIDENCE",
    "WORKFLOW_PHASE_SCHEMA_VERSION",
    "WORKFLOW_PHASES",
    "NoEvidence",
    "NormalizationError",
    "ResolutionIntegrityError",
    "ResolutionRecord",
    "GIT_ADAPTER_VERSION",
    "REPO_NORMALIZER_VERSION",
    "REFERENCE_JOIN_NORMALIZER_VERSION",
    "SESSION_TIMING_NORMALIZER_VERSION",
    "RefEvidence",
    "ReferenceTargetJoin",
    "SessionTiming",
    "RepoTarget",
    "VerifiedRecord",
    "VerifiedRepoSnapshot",
    "VerifiedSession",
    "WorktreeEvidence",
    "WorkflowPhase",
    "classify_workflow_phases",
    "normalize_claude",
    "normalize_codex",
    "normalize_repo_evidence",
    "normalize_reference_target_joins",
    "normalize_session_timing_bytes",
    "normalize_session_timings",
    "resolve_content_pointer",
    "resolution_coverage",
    "token_accounting_includes",
    "validate_corpus_artifact",
    "validate_repo_corpus_artifact",
    "classify_forge_invocation",
    "validate_reference_target_corpus_artifact",
    "workflow_phase_artifact",
]
